pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from ..forms import AnswerForm
from pybo.models import Question, Answer

from .auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('create/<int:question_id>', methods =('POST', ))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)

    if form.validate_on_submit():
        content  = request.form['content']
        answer   = Answer(content=content, create_data=datetime.now(), user=g.user )
        question.answer_set.append(answer)
        db.session.commit()
        return redirect( url_for('question.detail', question_id=question.id))
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('modify/<int:answer_id>', methods =('POST', 'GET' ))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question.id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)


@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from werkzeug.utils import secure_filename # for fileupload Function

from .. import db
from ..forms import QuestionForm, AnswerForm
from ..models import Question

from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')

# 질문들을 리스팅한다.
@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)  # 페이지
    #database에서 자료들(lists)을 가져온다.
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    #보여줄 자료를 만든 후(전달 대상(context), question_list)에 보여주는 것( html) 을 호출한다.
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    # 특정 한 개의 질문사항...
    question = Question.query.get_or_404(question_id)
    # 질문에 대한 상세 정보를 출력한다.  질문에 대한 내용과. 그에 따른 답변사항.. 및 새로운 답변을 달 수 있도록 Form 로 연결해서 보낸다.
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)


@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect( url_for('question._list'))


@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    #질문 등록할 수 있는 Form ...
    form = QuestionForm()
    # requests는 자동은로 넘어오고, 잡근 가능한듯..Routing...
    if request.method == 'POST' and form.validate_on_submit():
        # form문에서 넘어오면..(submit 후).... 데이터베이스 모델...Question.. 을 생성...models.py...
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)


#파일업로드 처리
@bp.route('/FileUpload', methods=('GET', 'POST'))
def upload_file():
    form = QuestionForm()
    if request.method == 'POST':
        f = request.files['file']
        #저장할 경로 + 파일명
        f.save( secure_filename(f.filename) )
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

pybo/templates/question/question_detail.html
<!--
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
-->
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <!-- 여기서 question은 한 개의 질문이다. 상세 정보 .. -->
    <!-- 질문 : 제목 -->
    <h2 class="border-bottom py-2"> {{ question.subject }} </h2>
    <div class="card my-3">
        <div class="card-body">
            <!-- 질문 : 내용 -->
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge baged-light p-2 text-left">
                    <div class="mb-2">{{ question.user.username }}</div>
                    <!-- 질문이 생성된 날짜 정보 -->
                    <div> {{ question.create_date |datetime }} </div>
                </div>
            </div>
            {% if g.user == question.user %}
            <div class="my-3">
                <a href="{{ url_for('question.modify', question_id=question.id) }}"
                             class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
            </div>
            {% endif %}

        </div>
    </div>
    <!-- 질문에 대한 답변 사항..-->
    <h5 class="border-bottom my-3 py-2"> {{ question.answer_set|length }} 개의 답변이 있습니다. </h5>
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;"> {{ answer.content }} </div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.user.username }}</div>
                    <!-- 질문이 생성된 날짜 정보 -->
                    <div> {{ question.create_date |datetime }} </div>
                </div>
            </div>
            {% if g.user == answer.user %}
            <div class="my-3">
                <a href = "{{ url_for('answer.modify', answer_id=answer.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                    data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}

    <!-- 추가 답변을 받기 위한  Form 문 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post", class=""my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <!-- name과 id 는 아직 구분이 안됨...-->
            <!-- forms.py로 연결됨...-->
            <textarea {% if not g.user %}disabled{% endif %}
                    name = "content" id="content" class="form-control" rows = "15"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $(document).ready( function() {
        $(".delete").on('click', function(){
            if( confirm("정말로 삭제하시겠습니다?")){
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <form method="post" class="post-form my-3">
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% for field, errors in form.errors.items() %}
    <div class="alert alert-danger" role="alert">
        <strong> {{ form[field].label }}</strong>: {{ ', '.join(errors) }}
    </div>
    {% endfor %}
    <!-- 오류표시 End -->

    <div class="form-group">
      <label for="subject">제목</label>
      <input type="text" class="form-control" name="subject" id="id_subject"
            value="{{ form.subject.data or '' }}">

    </div>
    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" name="content" id="id_content" row="5">{{ form.content.data or '' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>

  <h5 class="my-3 border-bottom pb-3">파일업로드</h5>
  <form enctype="multipart/form-data" action="save_file.py" method="post">
  <p>음성파일: <input type="file" name="file"></p>
  <p><input type="submit" class="btn btn-primary" value="전송"></p>
  </form>

</div>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        <!-- 전달받은 context... question_list  -->
        {% if question_list %}
        {% for question in question_list.items %}
        <tr class="text-center">
            <!-- 질문사항(question) 번호 ... -->
            <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
            <!-- 질문사항(question) 제목..(하이퍼링크 제공..) ... -->
            <td class="text-left">
                <!-- Route 정보 : BluePorint의  네이밈에 대한 (.)함수로 접근????-->
                <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <!-- 질문사항(question).  답변사항... -->
                <span class="text-danger small ml-2">{{ question.answer_set|length }}</span>
                {% endif %}
            </td>
            <td>{{ question.user.username }} </td>
            <!-- 질문사항  질문이 등록된 시각 정보 -->
            <td>{{ question.create_date | datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

    <!-- 신규 등록 질문.. -->
    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}